repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.6
    hooks:
      - id: insert-license
        files: \.(py)
        args:
        - --license-filepath=.LICENSE.txt
      - id: insert-license
        files: (cpp)|(c)$
        args:
          - --license-filepath=.LICENSE.txt
          - --comment-style="/*| *| */"
      
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        exclude: conda/meta.yaml
      - id: check-xml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.3
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
