{% set data= load_setup_py_data() %}

package:
    name: lsst-efd-client
    version: {{ data.get('version') }}

source:
    path: ../

build:
    noarch: python
    script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

test:
    requires:
        - ts-conda-build =0.5
        - vcrpy
        - pytables
        - requests
        - fastavro
        - numpy
        - pandas
        - astropy
        - kafkit
        - aiohttp
        - aioinflux
    source_files:
        - pyproject.toml
        - src
        - tests
    commands:
        - pytest

requirements:
    host:
        - pip
        - python {{ python }}
        - setuptools {{ setuptools }}
        - setuptools_scm {{ setuptools_scm }}
    build:
        - python {{ python }}
        - setuptools {{ setuptools }}
        - setuptools_scm {{ setuptools_scm }}
    run:
        - python {{ python }}
        - setuptools {{ setuptools }}
        - setuptools_scm {{ setuptools_scm }}
        - requests
        - fastavro
        - numpy
        - pandas
        - astropy
        - kafkit
        - aiohttp
        - aioinflux
